
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import { getServerSession } from "next-auth";
import { redirect } from "next/dist/server/api-utils";
import "./globals.css";
import Providers from "./providers";
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const metadata = {
  icons: {
    icon: '/icon.png',
  },
};
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
  }) {
  
  const session = await getServerSession(authOptions)
  if(session?.user)redirect("/Home")
  return (
    <html data-theme="cupcake" lang="en">
      {" "}
      {/*todo:Add change theme func*/}
      <Providers>
        <body className="">{children}</body>
      </Providers>
    </html>
  );
}
